AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: BokuBot
Globals:
    Function:
        MemorySize: 512
        Timeout: 60
        Runtime: nodejs12.x
        AutoPublishAlias: Latest

Resources:
    BokuMentionLambda:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: mention-lambda/built/mention-lambda/src/
            Handler: index.handler
            Layers:
              - !Ref BokuBotDepLayer
            Events:
                BokuAPI:
                    Type: Api
                    Properties:
                        Path: /
                        Method: any
            Policies:
                - DynamoDBCrudPolicy:
                    TableName: !Ref BokuTable
                - DynamoDBCrudPolicy:
                    TableName: !Ref BokuMemeFeedbackTable
            Environment:
                Variables:
                    SLACK_ACCESS_TOKEN: '{{resolve:ssm:BOKU_BOT_SLACK_ACCESS_TOKEN:1}}'
                    SLACK_VERIFICATION_TOKEN: '{{resolve:ssm:BOKU_BOT_SLACK_VERIFICATION_TOKEN:1}}'
                    IMAGE_FLIP_USERNAME: '{{resolve:ssm:IMAGE_FLIP_USERNAME:1}}'
                    IMAGE_FLIP_PASSWORD: '{{resolve:ssm:IMAGE_FLIP_PASSWORD:1}}'
                    DYNAMO_TABLE_NAME: !Ref BokuTable
                    BOKU_MEME_FEEDBACK_TABLE: !Ref BokuMemeFeedbackTable
                    GOOGLE_API_KEY: '{{resolve:ssm:GOOGLE_API_KEY:1}}'
                    GOOGLE_SEARCH_ENGINE_ID: '{{resolve:ssm:GOOGLE_SEARCH_ENGINE_ID:1}}'

    BokuActionLambda:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: action-lambda/built/action-lambda/src
            Handler: index.handler
            Layers:
                - !Ref BokuBotDepLayer
            Events:
                BokuAPI:
                    Type: Api
                    Properties:
                        Path: /action
                        Method: any
            Policies:
                - DynamoDBCrudPolicy:
                    TableName: !Ref BokuMemeFeedbackTable
            Environment:
                Variables:
                    BOKU_MEME_FEEDBACK_TABLE: !Ref BokuMemeFeedbackTable

    BokuBotDepLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: boku-bot-dependencies
            Description: Dependencies for boku bot
            ContentUri: dependencies/
            CompatibleRuntimes:
              - nodejs12.x
            LicenseInfo: 'MIT'
            RetentionPolicy: Retain

    BokuTable:
        Type: AWS::Serverless::SimpleTable
        Properties:
            PrimaryKey:
                Name: SlackMessageId
                Type: String
            ProvisionedThroughput:
                ReadCapacityUnits: 10
                WriteCapacityUnits: 10
            TableName: BokuRequestsTable
            Tags:
                Name: BokuTable

    BokuMemeFeedbackTable:
        Type: AWS::DynamoDB::Table
        Properties:
            KeySchema:
                -
                    AttributeName: UserId
                    KeyType: HASH
                -
                    AttributeName: ImageUrl
                    KeyType: RANGE
            AttributeDefinitions:
                -
                    AttributeName: ImageUrl
                    AttributeType: S
                -
                    AttributeName: UserId
                    AttributeType: S
            ProvisionedThroughput:
                ReadCapacityUnits: 10
                WriteCapacityUnits: 10
            TableName: BokuMemeFeedback
            Tags:
                -
                    Key: Name
                    Value: BokuMemeFeedbackTable

Outputs:
    ApiURL:
        Description: "API endpoint URL"
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/resource/"
