AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: BokuBot
Globals:
    Function:
        Timeout: 3
        Runtime: nodejs12.x

Resources:
    BokuLambda:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: built/src/
            Handler: index.handler
            Layers:
              - !Ref BokuBotDepLayer
            Events:
                BokuAPI:
                    Type: Api
                    Properties:
                        Path: /
                        Method: any
            Environment:
                Variables:
                    SLACK_ACCESS_TOKEN: '{{resolve:ssm:BOKU_BOT_SLACK_ACCESS_TOKEN:1}}'
                    SLACK_VERIFICATION_TOKEN: '{{resolve:ssm:BOKU_BOT_SLACK_VERIFICATION_TOKEN:1}}'
                    IMAGE_FLIP_USERNAME: '{{resolve:ssm:IMAGE_FLIP_USERNAME:1}}'
                    IMAGE_FLIP_PASSWORD: '{{resolve:ssm:IMAGE_FLIP_PASSWORD:1}}'

    BokuBotDepLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: boku-bot-dependencies
            Description: Dependencies for boku bot
            ContentUri: dependencies/
            CompatibleRuntimes:
              - nodejs12.x
            LicenseInfo: 'MIT'
            RetentionPolicy: Retain
