AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: BokuBot
Globals:
    Function:
        Timeout: 3
        Runtime: nodejs12.x
Parameters:
    pSomeSecret:
        Description: 'This is a parameter you pass when building the thing'
        Type: 'String'
        MinLength: 10
        AllowedPattern: '[a-zA-z0-9]+'
Resources:
    rBokuLambda:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: index.handler
            Layers:
              - !Ref rBokuBotDepLayer
            Events:
                BokuAPI:
                    Type: Api
                    Properties:
                        Path: /
                        Method: any
            Environment:
                Variables:
                    MY_SECRETE: !Ref pSomeSecret
    rBokuBotDepLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            LayerName: 'boku-bot-dependencies'
            Description: 'Dependencies for boku bot'
            ContentUri: dependencies/
            CompatibleRuntimes:
              - nodejs12.x
            LicenseInfo: 'MIT'
            RetentionPolicy: Retain
